export {
  faLocationDot,
  faCartShopping,
  faBars,
  faTruck,
  faCheck,
  faTruckPickup,
  faBagShopping,
  faEdit,
  faTrash,
  faCirclePlus,
  faCreditCard,
  faBoxOpen,
  faMinus,
  faPlus,
} from "@fortawesome/free-solid-svg-icons";
